server:
  port: 8001
spring:
  application:
    name: cm-auth
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER:127.0.0.1:8848}
      username: nacos
      password: nacos
      config:
        file-extension: yaml
        import-check:
          enabled: false