[project]
name = "cm-ai"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.119.0",
    "langchain>=0.3.27",
    "langchain-openai>=0.3.35",
    "sse-starlette>=3.0.2",
    "uvicorn>=0.37.0",
]
